services:
    laravel.test:
        build:
            context: "./docker/8.4"
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: "sail-8.4/app"
        container_name: ${PROJECT_NAME}-app
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT}:8000" # Octane expõe na 8000
            - "${VITE_PORT}:${VITE_PORT}"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
        volumes:
            - ".:/var/www/html:cached"
        networks:
            - laravel_octane_base
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        image: "mysql/mysql-server:8.0"
        container_name: ${PROJECT_NAME}-mysql-db
        restart: unless-stopped
        ports:
            - "${FORWARD_DB_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: "${MYSQL_EXTRA_OPTIONS}"
        volumes:
            # - "sail-mysql:/var/lib/mysql"
            - ./docker/mysql:/var/lib/mysql
        networks:
            - laravel_octane_base
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            interval: 10s
            retries: 5
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: ${PROJECT_NAME}-phpmyadmin
        restart: unless-stopped
        ports:
            - "${PHPMYADMIN_PORT}:80"
        environment:
            PMA_HOST: mysql
            # PMA_USER: "${DB_USERNAME}"
            #PMA_PASSWORD: "${DB_PASSWORD}"
            UPLOAD_LIMIT: 300M
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - laravel_octane_base

networks:
    laravel_octane_base:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
